---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cars":
    post:
      summary: Creates a new car
      tags:
      - Cars
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      description:
                        type:
                        - string
                        - 'null'
                      cost_per_day:
                        type: number
                      image:
                        type:
                        - string
                        - 'null'
                      created_at:
                        type: string
                        format: date_time
                      updated_at:
                        type: string
                        format: date_time
                    required:
                    - id
                    - name
                    - cost_per_day
                    - created_at
                    - updated_at
                required:
                - status
                - message
                - data
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: array
                        items:
                          type: string
                      cost_per_day:
                        type: array
                        items:
                          type: string
                      description:
                        type: array
                        items:
                          type: string
                      image:
                        type: array
                        items:
                          type: string
                required:
                - status
                - message
                - data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type:
                  - string
                  - 'null'
                cost_per_day:
                  type: number
                image:
                  type:
                  - string
                  - 'null'
              required:
              - name
              - cost_per_day
    get:
      summary: Retrieves all cars
      tags:
      - Cars
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        description:
                          type:
                          - string
                          - 'null'
                        cost_per_day:
                          type: number
                        image:
                          type:
                          - string
                          - 'null'
                        created_at:
                          type: string
                          format: date_time
                        updated_at:
                          type: string
                          format: date_time
                      required:
                      - id
                      - name
                      - cost_per_day
                      - created_at
                      - updated_at
                required:
                - status
                - message
                - data
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: 'null'
                required:
                - status
                - message
  "/api/v1/cars/{id}":
    delete:
      summary: Deletes a car by ID
      tags:
      - Cars
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      description:
                        type:
                        - string
                        - 'null'
                      cost_per_day:
                        type: number
                      image:
                        type:
                        - string
                        - 'null'
                      created_at:
                        type: string
                        format: date_time
                      updated_at:
                        type: string
                        format: date_time
                    required:
                    - id
                    - name
                    - cost_per_day
                    - created_at
                    - updated_at
                required:
                - status
                - message
                - data
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: 'null'
                required:
                - status
                - message
  "/api/v1/car/{id}":
    get:
      summary: Retrieves a car by ID
      tags:
      - Cars
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      description:
                        type:
                        - string
                        - 'null'
                      cost_per_day:
                        type: number
                      image:
                        type:
                        - string
                        - 'null'
                      created_at:
                        type: string
                        format: date_time
                      updated_at:
                        type: string
                        format: date_time
                    required:
                    - id
                    - name
                    - cost_per_day
                    - created_at
                    - updated_at
                required:
                - status
                - message
                - data
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                required:
                - status
                - message
  "/api/v1/users/{:user_username}/reservations":
    post:
      summary: Creates a new reservation
      tags:
      - Reservations
      parameters:
      - name: user_username
        in: path
        required: true
        schema:
          type: string
      - name: car_id
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: string
                cost:
                  type: number
                car_id:
                  type: integer
                user_id:
                  type: integer
                starting_date:
                  type: string
                  format: date-time
                end_date:
                  type: string
                  format: date-time
              required:
              - starting_date
              - end_date
  "/Api/v1/users/{user_username}/reservations":
    get:
      summary: Retrieves all reservations for a user
      tags:
      - Reservations
      parameters:
      - name: user_username
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        user_id:
                          type: integer
                        car_id:
                          type: integer
                        starting_date:
                          type: string
                          format: date
                        end_date:
                          type: string
                          format: date
                        created_at:
                          type: string
                          format: date_time
                        updated_at:
                          type: string
                          format: date_time
                      required:
                      - id
                      - user_id
                      - car_id
                      - starting_date
                      - end_date
                      - created_at
                      - updated_at
                required:
                - status
                - message
                - data
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: 'null'
                required:
                - status
                - message
  "/Api/v1/users/{username}":
    parameters:
    - name: username
      in: path
      description: username
      required: true
      schema:
        type: string
    get:
      summary: show user
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      full_name:
                        type:
                        - string
                        - 'null'
                      created_at:
                        type: string
                        format: date_time
                      updated_at:
                        type: string
                        format: date_time
                    required:
                    - id
                    - username
                    - full_name
                    - created_at
                    - updated_at
                required:
                - status
                - message
                - data
    delete:
      summary: delete user
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      full_name:
                        type:
                        - string
                        - 'null'
                      created_at:
                        type: string
                        format: date_time
                      updated_at:
                        type: string
                        format: date_time
                    required:
                    - id
                    - username
                    - full_name
                    - created_at
                    - updated_at
                required:
                - status
                - message
                - data
  "/Api/v1/users":
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                full_name:
                  type: string
              required:
              - username
              - full_name
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
